### ISSUE TITLE
osutils.ensure_dirs(), multiple issues

### ISSUE THREAD

**Issue by mgorny** [pkgcore/snakeoil#14]
Reading the spaghetti inside, I can see at least a few big issues:

* the dumb-return logic doesn't provide a way to figure out what the exact failure was.
* The parent-children iteration doesn't work as expected when symlinks are in the way. I mean, it checks only one of the parent trees, not the symlink target one.
* The code unnecessarily tries to force `+w` on all directories. Only immediate `mkdir()` parent needs `+w`, non-immediate parents need `+x` only.
* And at the same time, it assumes `u+wx` will be enough without checking the owner.
* `sticky_parent = (st.st_gid & stat.S_ISGID)` -- shouldn't this check `st.st_mode`?
* Permission resets are never executed when something inside the loop fails (immediate `return`).
* The post-reset `chown()` is terribly confusing. What directory is it supposed to `chown()` exactly? It looks like it'd catch the last directory which was `chmod()`-ed or `mkdir()`-ed. Please note that in case of race between two processes creating the directory, the final directory may already exist inside the loop.
* The whole thing looks like a terrible race condition candidate capable of messing up the filesystem good. But I guess that's inevitable.

I'd honestly drop all the smart ass logic there as it is just asking for trouble but that's just me. If parents are not `+wx` as appropriate, just let it fail. Trying to reproduce system logic for deducing `mkdir()` access is at least sloppy, and trying to work-around it is at least undesired.

**Comment by radhermit** [comment]
Is this still relevant, or did your pullreqs a while ago fix most of the main issues?

**Comment by mgorny** [comment]
I guess we can consider this fixed.
