### ISSUE TITLE
fileutils: fix AtomicWriteFile to work as expected when used as a context manager

### ISSUE THREAD

**Issue by radhermit** [pkgcore/snakeoil#18]
Currently usage such as the following:

``` python
with AtomicWriteFile('blah') as f:
    f.write('blah')
```

errors out with:

AttributeError: __exit__

due to the use of the WeakRefFinalizer metaclass that causes the __exit__ and __enter__ methods to not be defined on type(f) which in this case is snakeoil.obj.CustomDelayedObject.

**Comment by mgorny** [comment]
Why do we need this weakref magic on `AtomicWriteFile` anyway?

**Comment by ferringb** [comment]
It was a protection to ensure the file was cleaned up *always*, even if used incorrectly.  Note this code proceeds the era of context managers; that said, context managers are only as good as the consuming code- this implementation by virtue of proceeding that, didn't rely on assuming people got things right.

...Just answering the question there, not advocating a stance on what to do with the code there.

**Comment by mgorny** [comment]
Oh, right, I forgot that Python lacks sane design :).

**Comment by radhermit** [comment]
Closing since I think it should work as a context manager these days, at least it works fine for pkgcheck.
