### ISSUE TITLE
src/posix.c: HAVE_STAT_TV_NSEC seems not to be declared anywhere

### ISSUE THREAD

**Issue by mgorny** [pkgcore/snakeoil#21]
Looking through the code in `src/posix.h`, I see:

```
#ifdef HAVE_STAT_TV_NSEC
    self->mtime_nsec = st.st_mtim.tv_nsec;
#else
    self->mtime_nsec = 0;
#endif
````

But there's no platform check defining the define!

**Comment by radhermit** [comment]
Closing since I think the related fixes were merged a while ago.
