### ISSUE TITLE
klass: JIT-ing attributes overrides an attribute's docstring with the generic JIT docstring

### ISSUE THREAD

**Issue by radhermit** [pkgcore/snakeoil#30]
This is annoying for generated docs and similar. For an example see the EAPI.is_supported docstring at http://pkgcore.readthedocs.org/en/latest/api/pkgcore.ebuild.eapi.html

**Comment by ferringb** [comment]
eh, pardon the noise; had some issues w/ local tests.  The above will force docstrings to be available- however, it doesn't fix the scenario for pydoc.  Pydoc specifically does an internal isinstance(property, obj) check when deciding whether to display docstring data for a property.

The design can be reworked to be property based, although doing so has trade offs; I'm exploring that angle now.

**Comment by ferringb** [comment]
There is a slight performance decrease to using property (multiple layers of calls pretty much) in comparison to what was written... and this is a change of API.

If jit_attr cuts over to a property based implementation, then .singleton and friends are no longer accessible.  In the original days of this being written, that was of use- it allowed for violations of encapsulation by code that knew what it was doing.  I can't find any case of it now however.

**Comment by ferringb** [comment]
Let me know how this solution works for readthedocs; if it needs to be property based, I've got a notion, but will implement it a bit later.  Barring that, if you're happy with it, feel free to merge the PR

**Comment by radhermit** [comment]
Heh, yeah I'm not a huge fan of github's "feature" of crosslinking refs betweens repos. :smile: 

It looks like this should work for rtd which one can simulate locally by doing something similar to the following in the pkgcore repo root dir:

PYTHONPATH=/path/to/dir/containing/snakoil/module ./setup.py build_docs

which should run sphinx, build all the html docs, and place them in the build dir.

However, it appears that the native vs the C extension have a slight difference between them in that the native impl will drop in the JIT docstring if the target docstring doesn't exist while the C extension won't. Therefore, shouldn't the native impl unconditionally set __doc__ (i.e. drop the "if doc is not None" conditional) similar to what the C extension does?
