### ISSUE TITLE
Unicode Decode Error - pkgcore - gentoo

### ISSUE THREAD

**Issue by eyoung100** [pkgcore/snakeoil#49]
See attachment.  I'd like to migrate to pkgcore.  I have no conf file, so the info is pulled from portage,

Steps to reproduce (Success):

1. Login as a user on GNOME3 w/ systemd
2. `sudo -i` in gnome-terminal
3. `pmaint sync && pmerge --ask --upgrade --deep --newuse` as per the [Wiki Article
](https://wiki.gentoo.org/wiki/Pkgcore)

Steps to reproduce (Failure):
1. Switch to a plain TTY using `Ctrl + F2`
2. Repeat the above steps in Success starting with 2.

Note that logging in directly as root, pr as my user and using `sudo -i` produces the result in the attachment.  What's different between GNOME Terminal vs. a plain TTY?

[SnakeoilTraceback.txt](https://github.com/pkgcore/snakeoil/files/3854866/SnakeoilTraceback.txt)

**Comment by radhermit** [comment]
Should be fixed by https://github.com/pkgcore/snakeoil/commit/72206db8d0d20fd3feeeb64da485103259bb2707.
