### ISSUE TITLE
snakeoil 0.5.3 release doesn't include read_dict movement

### ISSUE THREAD

**Issue by dastergon** [pkgcore/snakeoil#6]
Hello,

 snakeoil 0.5.3 release does not include the `read_dict` movement from `snakeoil.fileutils` to `snakeoil.bash`( ba20ab2902e1db0205cb2c4ef89f9be913392df7 - November 2013 ) which happened earlier than the last release (April 2014).

A new release would be great.

Thanks in advance,
Pavlos

**Comment by radhermit** [comment]
Just so things are clear, making a new snakeoil release generally means making new pkgcore and pkgcore-checks releases which is currently slowing things down a bit. That should change in the future once I fix a few more pkgcore bugs and can then make useful releases more regularly.

**Comment by radhermit** [comment]
0.6.1 now on pypi and in the tree.
