### ISSUE TITLE
Remove distutils_extensions.py

### ISSUE THREAD

**Issue by arthurzam** [pkgcore/snakeoil#77]
For snakeoil v10, I want to fully remove `distutils_extensions.py`, and just use some plain build back-end.

Ideally I want to use `flit`, but I guess it is impossible to use for pkgcheck (as we need to build tree-sitter-bash there).

There will be also need for some "main command executor", but I think a plain Makefile will be good enough (pytest, pylint, sphinx man, sphinx html, install, wheel, sdist, ...)

**Comment by mgorny** [comment]
I think `flit` would work if you made tree-sitter-bash built-on-import.

**Comment by arthurzam** [comment]
@mgorny Thanks for the input and encouragement. I will start the work across the stack, and when it looks good will call you for review 😄 


> I think `flit` would work if you made tree-sitter-bash built-on-import.

Can you please give some more info about this idea, or an example package that does that? Or maybe I misunderstood a lot and it is already implemented at the logic here?

https://github.com/pkgcore/pkgcheck/blob/f62212223635d8160dd848f96158a9d80d532715/src/pkgcheck/bash/__init__.py#L22-L87

**Comment by mgorny** [comment]
Yes, that's the logic. I haven't tested that but I think it'd work if you called `build_library` from `pkgcore/__init__.py` — i.e. when flit_core imported it to get the version, it'd build the library.

**Comment by arthurzam** [comment]
Update on progress:

1. as part of removal of this module, I needed to extract and cleanup the docs generation process, so I developed small sphinx extension to handle all the weird code https://github.com/pkgcore/snakeoil/pull/89
2. `snakeoil` is using pure `flit`
3. `pkgcore` is already using `flit` with custom wrapper to handle some extra file generation. This approach will be needed for other parts of stack.
4. `pkgdev` is ready to be moved to `flit` after new release of snakeoil with sphinx extension is done. It was a simple one without issues.
5. `pkgcheck` will need some extra work!

## pkgcheck migration
pkgcheck bundles in the wheel `libtree-sitter-bash.so`, which is dependent on CPU arch + libc (so not universal) but doesn't link or use python libs, so it can be agnostic to python version.
`flit` only support universal wheels (it hard codes `py3-none-any.whl`). So I have 2 options:

1. Use `flit`, and wrap *after* wheel generation, to rename the wheel, and open it's insides to edit `WHEEL` file and replace the tag with `Tag: py3-none-any`.
2. Use simple setuptools (in the most simple way), so it creates for me the arch dependent wheel.

I hope for some more input on this, which is preferable?

**Comment by mgorny** [comment]
I think the latter would be better.

**Comment by arthurzam** [comment]
Update: the module is unused and was marked as deprecated. I think in some releases it will be removed finally.
