### ISSUE TITLE
Headers are not installed properly in virtualenv

### ISSUE THREAD

**Issue by mgorny** [pkgcore/snakeoil#8]
virtualenv test
    . test/bin/activate
    pip install snakeoil

You would expect the headers in `test/include/site/python2.7/snakeoil`. But they're in top-level `test/include/site/python2.7` instead.

**Comment by radhermit** [comment]
I'm pretty sure this is a pip issue, see https://github.com/pypa/pip/blob/develop/pip/req/req_install.py#L790

**Comment by mgorny** [comment]
Jeez, distutils is stupid enough to invent subdir in include itself… Now you just gotta convince pip upstream :P.

**Comment by radhermit** [comment]
Pull request opened upstream: https://github.com/pypa/pip/pull/2421

**Comment by radhermit** [comment]
Closing since >=pip-6.1.0 should include the change.
